import { Metadata } from "next";
import "./global.css";
export const metadata:Metadata = {
  title: {
    default:"Nextjs Learn",
    template:"%s | ahmed",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header className="bg-cyan-500 p-2 w-screen h-full ">Header</header>
        {children}
        <footer className="bg-cyan-700 p-2 w-screen h-full">Footer</footer>
        </body>
    </html>
  );
}
